name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

  pipelines:
  - pipeline: build_pipeline
    source: "Ambulance-Analytics-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: true
    enable_status_monitoring: true
    apigee_deployments:
        - environment: internal-dev
          make_spec_visible: true
          post_deploy:
            - template: templates/tests.yml
              parameters:
                environment: 'internal-dev'
                service_name: ${{ variables.service_name }}
                base_url: 'internal-dev.api.service.nhs.uk'
        - environment: internal-qa
          make_spec_visible: true
        - environment: internal-qa-sandbox
          proxy_path: sandbox
          make_spec_visible: true
        - environment: int
          make_spec_visible: true
          depends_on:
              - internal_qa
              - internal_qa_sandbox
          post_deploy:
            - template: templates/tests.yml
              parameters:
                environment: 'int'
                service_name: ${{ variables.service_name }}
                base_url: 'int.api.service.nhs.uk'
        - environment: sandbox
          proxy_path: sandbox
          depends_on:
              - internal_qa
              - internal_qa_sandbox
        - environment: prod
          proxy_path: live
          make_spec_visible: true
          depends_on:
              - int
              - sandbox
          post_deploy:
              - template: templates/smoke-tests.yml
                parameters:
                    environment: 'prod'
                    service_name: ${{ variables.service_name }}
                    base_url: 'api.service.nhs.uk'
