variables:
  service_name: ambulance-analytics
  service_base_path: ambulance-analytics
  short_service_name: ambulance-analytics
  product_display_name: Ambulance Analytics
  product_description: " "
  spec_file: ambulance-analytics.json
