openapi: 3.0.0
info:
  version: v1.0.98-alpha
  title: Ambulance Analytics - FHIR API
  description: |
    ## Overview
    Use this API to submit ambulance analytics data to our Data Processing Service (DPS) so that it can be made available for analysis and review by NHS England and ambulance trusts.

    Ambulance analytics data is information relating to emergency calls (999, 111 and others), received at an Emergency Operations Centre (EOC) and processed into a Computer Aided Despatch (CAD) system, including:
      - call details
      - response details - including response times and episode outcome times patient
      - contact details - including patient demographics, patient response details, patient information, injury information, patient assessment, medication, observations, diagnoses, conveying outcome, safeguarding and public health information

    You can:
      - post ambulance analytics data individually or in batches

    You cannot:
      - read any of the records stored in DPS

    The API is asynchronous - to receive error notifications, you need to use [MESH](https://digital.nhs.uk/services/message-exchange-for-social-care-and-health-mesh). The following diagram illustrates the end-to-end process:

    ![Ambulance Overview](https://github.com/NHSDigital/ambulance-analytics-api/blob/master/specification/diagrams/APIAsynchE2eProcess.PNG?raw=true)

    The following describes the end-to-end process:
    1. the Ambulance Trust System sends the ambulance analytics data to the Ambulance Analytics API
    2. the Ambulance Analytics API forwards the ambulance analytics data to our Data Processing System (DPS)
    3. if there is an error, DPS sends an error notification to MESH
    4. the Ambulance Trust System retrieves the error notification from MESH
    5. an Analytics User views ambulance analytics data in our NHS Digital Analytics Dashboards
    6. the NHS Digital Analytics Dashboards get the ambulance analytics data from DPS

    ## Legal Use
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see ‘Onboarding’ below).

    ## Related APIs
    Use [Messaging Exchange for Social care and Health (MESH)](https://meshapi.docs.apiary.io/) to receive error notifications from DPS for this API

    ## API status and roadmap
    This API is in [private beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:
      * we might make breaking changes, but only if we can't avoid it, and we'll give advance notice
      * we can't guarantee availability or performance
      * it is available for production use, but only to a small group of ambulance trusts in England

    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=allexceptdone&tag=ambulance-analytics&deleted=0#controls).

    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Technology
    This API uses HTTP POST to submit data.

    The data payload conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4. To see the FHIR message payload, see the [Ambulance Data Set FHIR Implementation Guide](https://simplifier.net/Ambulance/~guides)

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details, see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    ### Application-restricted access
    This access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis),
    meaning we authenticate the calling application but not the end user.

    You can use this access mode as follows:
    * unattended (end user not present), for example as part of a back end process to check NHS numbers for data flowing from one system to another

    To use this access mode, use the following security pattern:
    * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    - is for early developer testing
    - only covers a limited set of scenarios
    - is stateless, so it does not actually persist any updates
    - is open access, so does not allow you to test authorisation

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    - is for formal integration testing

    ## Onboarding

    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.

    To onboard for this API, follow the [Supplier Conformance Assessment List](https://digital.nhs.uk/developer/guides-and-documentation/onboarding-process#onboard-using-the-supplier-conformance-assessment-list-scal-process) (SCAL) process.

    When following the SCAL process, note that:

    * In step 8: you need to review and complete the Ambulance Analytics API risk log to show that you have understood and mitigated the various risks. You might be asked to provide some evidence to prove that controls have been put in place. You’ll find the risk log embedded within the Ambulance Analytics API tab in the SCAL.
    * In step 10: when you complete the Service Desk Registration Form, send it to [api.management@nhs.net](mailto:api.management@nhs.net).
    * In step 11: submit your completed SCAL to [api.management@nhs.net](mailto:api.management@nhs.net).
    * In step 14: to request production access, contact us at [api.management@nhs.net](mailto:api.management@nhs.net).

  contact:
    name: API Management Support
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/ambulance-analytics'
    description: Sandbox environment.
tags:
  - name: Ambulance Analytics Api
paths:
  /submission:
    post:
      summary: Submit ambulance analytics data
      operationId: postData
      description: |
        ## Overview
        Use this endpoint to submit ambulance analytics data to DPS. This endpoint does not validate the submitted payload, it only acknowledges receipt of the payload.
        See the [FHIR implementation guide](https://simplifier.net/Ambulance/~guides) for how to structure the payload data.
      responses:
        '200':
          description: Data received and sent to DPS.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                Example:
                  value:
                    message: 6eeec54e-3d39-4bc4-a1d9-57615d258fpq
      tags:
        - Post ambulance data
      parameters: []
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
