# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "0.0.1"
  title: Ambulance Analytics API
  description: |
    ## Overview
    This API is designed for posting data to DPS regarding any event within a timeline of when a patient deals with an Ambulance.
    
    You can:
    - Post data.

    You cannot currently use this API to:
    - For any kind of search function
    - Posting any other sorts data (ambulance only)

    ## Using this API
    This API follows the OAuth 2.0 protocol so in order to successfully post data a valid access token is required.
    In order to get an access token a signed JWT token must be successfully validated and only then will an access token be granted.
    The current flow to use this API is:
      - GET request with a signed JWT token and other required headers to the /token endpoint
      - POST request with the access token in the Authorization header to /{x-dataset-id}
    
    ## API status and roadmap
    The ambulance analytics API is planned to go into Alpha end of August 2020 and is currently deployed on the int environment.

    The following items are on our roadmap, in rough priority order:
      - Get to Beta stage and tested (hopefully end of September 2020)

    We look forward to recieving feedback once the API is in Alpha/Beta.


    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).

    It also conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    This API is available on the Internet, although access using NHS smartcards (see below)
    currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    This API follows the OAuth 2.0 protocol, although a user doesn't need to be present to use this API all they need is to send a JWT token signed with a private key with the RS256 algorithm.
    Once the target server receives the JWT token it will lookup a set of public keys from a url or store and check each public key until it finds one that matches.
    Refer to documentation for more information.

    Currently this API is targeted at developers that work for NHS Ambulance Trusts but this is subject to change.
    
    ## Testing
    You can test this API in:
    * our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing) for initial developer testing
    * our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing) for formal integration testing

    Our sandbox environment is a very basic simulation of the live service. It only covers a limited set of scenarios and is stateless, so does not actually persist any updates.

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Also, there are plans to try out the sandbox using a Postman collection:

    ## Assurance
    We are hoping to make the assurance process as lightweight and as self-service as possible.

    ## Endpoints
    Currently the endpoints for the ambulance analytics API for testing within sandbox are:
          - POST /{x-dataset-id} used for posting ambulance data to DPS

    Authorisation within the sandbox is disabled which is why only the one endpoint is available for testing.

  contact:
    name: API Management Support
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/ambulance-data'
    description: Sandbox environment.
tags:
  - name: ambulance
paths:

  /x-dataset-id:
    post:
      summary: Post Ambulance Analytics data.
      operationId: postData
      description: |
        Get a 200 response with an empty response body "{}"

      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Test"
              example:
                message: "{}"
      tags:
        - Post ambulance data

components:
  schemas:
    Greeting:
      $ref: components/schemas/Greeting.yaml
